// Bundles the widget code (src/view/main.ts) into a single ESM string and emits it as a TypeScript
// module (src/generated/viewBundle.ts) so the server can inline it into the widget HTML. Generated
// output is gitignored; `npm run build` / `npm run dev` regenerate it.
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

const result = await build({
  entryPoints: [join(repoRoot, "src/view/main.ts")],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  write: false,
  define: { "process.env.NODE_ENV": '"production"' },
});

const js = result.outputFiles[0].text;

const moduleSource =
  "// Generated by scripts/build-view.mjs — do not edit by hand.\n" +
  `export const VIEW_BUNDLE_JS: string = ${JSON.stringify(js)};\n`;

const outDir = join(repoRoot, "src/generated");
await mkdir(outDir, { recursive: true });
await writeFile(join(outDir, "viewBundle.ts"), moduleSource);

console.log(`[build-view] src/generated/viewBundle.ts (${(js.length / 1024).toFixed(1)} KiB)`);
